In [1]:
import numpy as np

List vs Numpy - time taken

In [3]:
from time import process_time

time taken by a List

In [5]:
lst = [i for i in range (100000)]

start_time = process_time()

lst = [i+5 for i in lst]

end_time = process_time()

print(end_time - start_time)


0.015625


In [6]:
from time import process_time

In [7]:
np_ara = np.array([i for i in range (100000)])

start_time = process_time()

np_ara += 5

end_time = process_time()

print(end_time - start_time)

0.0


Numpy arrays

In [9]:
np_arr = np.array([1,2,3,4,5])
print(np_arr)
type(np_arr)


[1 2 3 4 5]


numpy.ndarray

In [10]:
len(np_arr)

5

In [11]:
np_arr.shape

(5,)

In [12]:
np_arr2 = np.array([(1,2,3),(4,5,6)])
print(np_arr2)

print("\n(row, col)")
np_arr2.shape


[[1 2 3]
 [4 5 6]]

(row, col)


(2, 3)

In [13]:
np_arr3 = np.array([(1,2,3),(4,5,6)],dtype = str) #datatype can be declared
print(np_arr3)


[['1' '2' '3']
 ['4' '5' '6']]


Initial placeholder in numpy arrays

In [15]:
#create numpy arrays of zero

z = np.zeros((4,5))
print(z)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
#array with specific value

x = np.full (( 5, 4), 5 )
print (x)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [17]:
#create an identity matrix

iden = np.eye( 5 )
print( iden )

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
#create an numpy array with random values

rndom = np.random.random(( 3, 4 ) )
print ( rndom )


[[0.8802574  0.40840838 0.11465934 0.89327789]
 [0.90541951 0.5249549  0.33552431 0.34017916]
 [0.42781458 0.38701295 0.83504656 0.89980822]]


In [19]:
#create an numpy array with random values within specific range
#np.random.randint( starting num, ending num, (row,col))

rm = np.random.randint( 10, 100, ( 3, 4 ) )
print( rm )


[[64 49 32 52]
 [93 71 18 67]
 [48 81 26 80]]


In [48]:
#array of evenly spaced values...the endpoint is included(its indicate size)

aray = np.linspace ( 10, 50, 5) # 5 ta number same space pore pore
print(aray)

aray1 = np.linspace ( 10, 50, 3)
print(aray1)

[10. 20. 30. 40. 50.]
[10. 30. 50.]


In [42]:
#Generates an array with a specified range and step size,The stop value is not included.

ary = np.arange ( 10, 50, 5) # 5 ghor pore pore
print(ary) 

[10 15 20 25 30 35 40 45]


In [54]:
#convert a list to numpy array

lst1 = [ 10, 20, 30, 35, 35, 40, 50 ]
np_ar = np.asarray(lst1)
print(np_ar)
type(np_ar)

[10 20 30 35 35 40 50]


numpy.ndarray

Analyzing a numpy array

In [74]:
s = np.array([1,2,3,4,5])
print(s)
print(s.shape)
print(s.ndim)
print(s.size)

[1 2 3 4 5]
(5,)
1
5


In [96]:
matrx = np.array([(1,2,3,4,5),(6,7,8,9,10),(11,12,13,14,15)])
print(matrx)
print("\n")
print('(row and column) = ',matrx.shape)
print('dimension of matrix: ',matrx.ndim)
print('size of matrix: ',matrx.size)
print('data type of the array:',matrx.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


(row and column) =  (3, 5)
dimension of matrix:  2
size of matrix:  15
data type of the array: int32


Mathmetical operation on a Numpy array

In [98]:
list3 = [4,5,6,7,0]
list4 = [8,9,10,11]
print(list3 + list4) #concatenate or joins list


[4, 5, 6, 7, 0, 8, 9, 10, 11]


In [104]:
#

X = np.random.randint( 0, 20, (3,3))
Y = np.random.randint( 20, 30, (3,3))

print(X,'\n')
print(Y)

[[ 1  9 12]
 [ 8  6 10]
 [ 1 19  4]] 

[[22 28 27]
 [28 26 21]
 [22 24 20]]


In [118]:
print('adding the matrix')
print(X+Y)

print('adding the matrix using np')
print(np.add(X,Y))

adding the matrix
[[23 37 39]
 [36 32 31]
 [23 43 24]]
adding the matrix using np
[[23 37 39]
 [36 32 31]
 [23 43 24]]


In [122]:
print('Subtracting the matrix')
print(X-Y)

print('subtracting the matrix using np')
print(np.subtract(X,Y))

Subtracting the matrix
[[-21 -19 -15]
 [-20 -20 -11]
 [-21  -5 -16]]
subtracting the matrix using np
[[-21 -19 -15]
 [-20 -20 -11]
 [-21  -5 -16]]


In [134]:
print('Multiplying the matrix')
print(X*Y)

print('Multiplying the matrix using np')
print(np.multiply(X,Y))

Multiplying the matrix
[[ 22 252 324]
 [224 156 210]
 [ 22 456  80]]
Multiplying the matrix using np
[[ 22 252 324]
 [224 156 210]
 [ 22 456  80]]


In [136]:
print('Division the matrix')
print(X/Y)

print('\ndivide the matrix using np')
print(np.divide(X,Y))

Division the matrix
[[0.04545455 0.32142857 0.44444444]
 [0.28571429 0.23076923 0.47619048]
 [0.04545455 0.79166667 0.2       ]]

divide the matrix using np
[[0.04545455 0.32142857 0.44444444]
 [0.28571429 0.23076923 0.47619048]
 [0.04545455 0.79166667 0.2       ]]


Array Manupulation

In [141]:
manp = np.random.randint(0,10,(2,3))
print(manp)
print('(row,col)=',manp.shape)

[[0 1 7]
 [4 4 9]]
(row,col)= (2, 3)


In [145]:
#transpose

trans  = np.transpose(manp)
print(trans)
print('(row,col)=',trans.shape)

[[0 4]
 [1 4]
 [7 9]]
(row,col)= (3, 2)


In [147]:
trans2  = manp.T
print(trans2)
print('(row,col)=',trans2.shape)

[[0 4]
 [1 4]
 [7 9]]
(row,col)= (3, 2)


In [151]:
# Reshaping an array
d = np.random.randint(2,9,(2,3))
print(d)
print('(row,col)=',d.shape)

[[8 2 7]
 [6 3 7]]
(row,col)= (2, 3)


In [153]:
e = d.reshape(3,2)
print(e)
print('(row,col)=',e.shape)

[[8 2]
 [7 6]
 [3 7]]
(row,col)= (3, 2)
